import { defineConfig } from "oxlint";

export default defineConfig({
    categories: {
        correctness: "deny",
        nursery: "deny",
        perf: "deny",
        restriction: "deny",
        style: "deny",
        suspicious: "deny",
    },
    env: {
        builtin: true,
    },
    ignorePatterns: ["tests/**", "dist/**", "main.js"],
    overrides: [
        {
            env: {
                node: true,
            },
            files: ["**/*.{js,mjs,cjs,ts,mts,cts}"],
            rules: {
                "constructor-super": "error",
                curly: ["deny", "multi-line"],
                eqeqeq: ["error", "always"],
                "for-direction": "error",
                "func-style": "off",
                "id-length": "off",
                "max-params": "off",
                "sort-imports": "off",
                "eslint/sort-keys": "off",
                "typescript/ban-ts-comment": "error",
                "typescript/ban-tslint-comment": "error",
                "unicorn/no-abusive-eslint-disable": "error",
                "no-bitwise": "off",
                "max-statements": ["error", { max: 30 }],
                "no-console": "off",
                "class-methods-use-this": "off",
                "no-async-promise-executor": "error",
                "no-case-declarations": "error",
                "no-class-assign": "error",
                "no-compare-neg-zero": "error",
                "no-cond-assign": "error",
                "no-const-assign": "error",
                "no-constant-binary-expression": "error",
                "no-constant-condition": "error",
                "no-continue": "off",
                "no-control-regex": "error",
                "no-debugger": "error",
                "no-delete-var": "error",
                "no-dupe-class-members": "error",
                "no-dupe-else-if": "error",
                "no-dupe-keys": "error",
                "no-duplicate-case": "error",
                "no-else-return": [
                    "error",
                    {
                        allowElseIf: false,
                    },
                ],
                "no-empty": "error",
                "no-undefined": "off",
                "no-empty-character-class": "error",
                "no-empty-pattern": "error",
                "no-empty-static-block": "error",
                "no-ex-assign": "error",
                "no-ternary": "off",
                "no-extra-boolean-cast": "error",
                "no-fallthrough": "error",
                "no-func-assign": "error",
                "no-global-assign": "error",
                "no-implicit-coercion": "error",
                "no-import-assign": "error",
                "no-invalid-regexp": "error",
                "no-irregular-whitespace": "error",
                "no-loss-of-precision": "error",
                "no-misleading-character-class": "error",
                "no-new-native-nonconstructor": "error",
                "no-nonoctal-decimal-escape": "error",
                "no-obj-calls": "error",
                "no-param-reassign": "error",
                "no-plusplus": "off",
                "no-prototype-builtins": "error",
                "no-redeclare": "error",
                "no-regex-spaces": "error",
                "no-self-assign": "error",
                "no-setter-return": "error",
                "no-shadow": "error",
                "no-shadow-restricted-names": "error",
                "no-sparse-arrays": "error",
                "no-this-before-super": "error",
                "no-unassigned-vars": "error",
                "no-unexpected-multiline": "error",
                "no-unsafe-finally": "error",
                "no-unsafe-negation": "error",
                "no-unsafe-optional-chaining": "error",
                "no-unused-labels": "error",
                "no-unused-private-class-members": "error",
                "no-use-before-define": [
                    "error",
                    {
                        classes: false,
                        functions: false,
                        variables: true,
                    },
                ],
                "no-useless-backreference": "error",
                "no-useless-catch": "error",
                "no-useless-concat": "error",
                "no-useless-escape": "error",
                "no-var": "error",
                "no-with": "error",
                "prefer-const": "error",
                "prefer-readonly-parameter-types": "off",
                "prefer-template": "error",
                "preserve-caught-error": "error",
                "require-yield": "error",
                "use-isnan": "error",
                "valid-typeof": "error",
            },
        },
        {
            files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
            rules: {
                "constructor-super": "error",
                "no-class-assign": "error",
                "no-const-assign": "error",
                "no-dupe-class-members": "error",
                "no-dupe-keys": "error",
                "no-func-assign": "error",
                "no-import-assign": "error",
                "no-new-native-nonconstructor": "error",
                "no-obj-calls": "error",
                "no-redeclare": "error",
                "no-setter-return": "off",
                "no-this-before-super": "error",
                "no-unsafe-negation": "error",
                "no-var": "error",
                "no-with": "error",
                "prefer-const": "error",
                "prefer-rest-params": "error",
                "prefer-spread": "error",
            },
        },
    ],
    plugins: ["typescript", "eslint", "unicorn"],
    rules: {
        "@typescript-eslint/adjacent-overload-signatures": "error",
        "@typescript-eslint/array-type": "error",
        "@typescript-eslint/await-thenable": "error",
        "@typescript-eslint/ban-ts-comment": [
            "error",
            {
                minimumDescriptionLength: 120,
            },
        ],
        "filename-case": "off",
        "@typescript-eslint/ban-tslint-comment": "error",
        "@typescript-eslint/class-literal-property-style": "error",
        "@typescript-eslint/consistent-generic-constructors": "error",
        "@typescript-eslint/consistent-indexed-object-style": [
            "error",
            "record",
        ],
        "@typescript-eslint/consistent-type-assertions": "error",
        "@typescript-eslint/consistent-type-definitions": "error",
        "@typescript-eslint/explicit-module-boundary-types": "error",
        "@typescript-eslint/no-array-delete": "error",
        "@typescript-eslint/no-base-to-string": "error",
        "@typescript-eslint/no-confusing-non-null-assertion": "error",
        "@typescript-eslint/no-confusing-void-expression": "error",
        "@typescript-eslint/no-deprecated": "error",
        "@typescript-eslint/no-duplicate-enum-values": "error",
        "@typescript-eslint/no-duplicate-type-constituents": "error",
        "@typescript-eslint/no-dynamic-delete": "error",
        "@typescript-eslint/no-empty-object-type": "error",
        "@typescript-eslint/no-explicit-any": "error",
        "@typescript-eslint/no-extra-non-null-assertion": "error",
        "@typescript-eslint/no-extraneous-class": "error",
        "@typescript-eslint/no-floating-promises": "error",
        "@typescript-eslint/no-for-in-array": "error",
        "@typescript-eslint/no-implied-eval": "error",
        "@typescript-eslint/no-inferrable-types": "error",
        "@typescript-eslint/no-invalid-void-type": "error",
        "@typescript-eslint/no-meaningless-void-operator": "error",
        "@typescript-eslint/no-misused-new": "error",
        "@typescript-eslint/no-misused-promises": "error",
        "@typescript-eslint/no-misused-spread": "error",
        "@typescript-eslint/no-mixed-enums": "error",
        "@typescript-eslint/no-namespace": "error",
        "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
        "@typescript-eslint/no-non-null-assertion": "error",
        "@typescript-eslint/no-redundant-type-constituents": "error",
        "@typescript-eslint/no-require-imports": "error",
        "@typescript-eslint/no-this-alias": "error",
        "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
        "@typescript-eslint/no-unnecessary-template-expression": "error",
        "@typescript-eslint/no-unnecessary-type-arguments": "error",
        "@typescript-eslint/no-unnecessary-type-assertion": "error",
        "@typescript-eslint/no-unnecessary-type-constraint": "error",
        "@typescript-eslint/no-unsafe-argument": "error",
        "@typescript-eslint/no-unsafe-assignment": "error",
        "@typescript-eslint/no-unsafe-call": "error",
        "@typescript-eslint/no-unsafe-declaration-merging": "error",
        "@typescript-eslint/no-unsafe-enum-comparison": "error",
        "@typescript-eslint/no-unsafe-function-type": "error",
        "@typescript-eslint/no-unsafe-member-access": "error",
        "@typescript-eslint/no-unsafe-return": "error",
        "@typescript-eslint/no-unsafe-unary-minus": "error",
        "@typescript-eslint/no-wrapper-object-types": "error",
        "@typescript-eslint/non-nullable-type-assertion-style": "error",
        "@typescript-eslint/only-throw-error": "error",
        "@typescript-eslint/prefer-as-const": "error",
        "@typescript-eslint/prefer-for-of": "error",
        "@typescript-eslint/prefer-function-type": "error",
        "@typescript-eslint/prefer-includes": "error",
        "@typescript-eslint/prefer-literal-enum-member": "error",
        "@typescript-eslint/prefer-namespace-keyword": "error",
        "@typescript-eslint/prefer-nullish-coalescing": "error",
        "@typescript-eslint/prefer-promise-reject-errors": "error",
        "@typescript-eslint/prefer-reduce-type-parameter": "error",
        "@typescript-eslint/prefer-return-this-type": "error",
        "unicorn/prefer-string-slice": "error",
        "@typescript-eslint/related-getter-setter-pairs": "error",
        "unicorn/no-useless-undefined": "error",
        "unicorn/prefer-math-trunc": "error",
        "unicorn/prefer-math-min-max": "error",
        "@typescript-eslint/require-await": "error",
        "@typescript-eslint/restrict-plus-operands": [
            "error",
            {
                allowAny: false,
                allowBoolean: false,
                allowNullish: false,
                allowNumberAndString: false,
                allowRegExp: false,
            },
        ],
        "@typescript-eslint/restrict-template-expressions": [
            "error",
            {
                allowAny: false,
                allowBoolean: false,
                allowNever: false,
                allowNullish: false,
                allowNumber: true,
                allowRegExp: false,
            },
        ],
        "@typescript-eslint/return-await": [
            "error",
            "error-handling-correctness-only",
        ],
        "@typescript-eslint/switch-exhaustiveness-check": "error",
        "@typescript-eslint/triple-slash-reference": "error",
        "@typescript-eslint/unbound-method": "error",
        "@typescript-eslint/unified-signatures": "error",
        "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
        "eslint/no-magic-numbers": [
            "error",
            {
                ignoreEnums: true,
                ignoreDefaultValues: true,
                ignoreNumericLiteralTypes: true,
                ignoreReadonlyClassProperties: true,
                ignoreTypeIndexes: true,
                ignoreClassFieldInitialValues: true,
                ignoreArrayIndexes: true,
                ignore: [0, 1, 2],
            },
        ],
        "no-array-constructor": "error",
        "no-empty-function": "error",
        "no-unused-expressions": "error",
        "no-unused-vars": "error",
        "no-useless-constructor": "error",
    },
    settings: {
        jsdoc: {
            augmentsExtendsReplacesDocs: false,
            exemptDestructuredRootsFromChecks: false,
            ignoreInternal: false,
            ignorePrivate: false,
            ignoreReplacesDocs: true,
            implementsReplacesDocs: false,
            overrideReplacesDocs: true,
            tagNamePreference: {},
        },
        "jsx-a11y": {
            attributes: {},
            components: {},
        },
        next: {
            rootDir: [],
        },
        react: {
            componentWrapperFunctions: [],
            formComponents: [],
            linkComponents: [],
        },
        vitest: {
            typecheck: false,
        },
    },
});
