import * as lib from "./lib.js";
import { runKeywordsTests } from "./keywords.js";
import { runLiteralsTests } from "./literals.js";
import { runOperatorsTests } from "./operators.js";
import { runDelimitersTests } from "./delimiters.js";
import { runCommentsTests } from "./comments.js";
import { runErrorsTests } from "./errors.js";
import { runPositionTests } from "./position.js";
import { runAstTests } from "./ast.js";
import { runParserExpressionTests } from "./parser/expressions.js";
import { runParserStatementTests } from "./parser/statements.js";
import { runParserItemTests } from "./parser/items.js";
import { runParserPatternTests } from "./parser/patterns.js";
import { runParserTypeTests } from "./parser/types.js";
import { runParserErrorTests } from "./parser/errors.js";
import { runTypeRepresentationTests } from "./types/representation.js";
import { runTypeContextTests } from "./types/context.js";
import { runTypeUtilitiesTests } from "./types/utilities.js";
import { runHirConstructionTests } from "./hir/construction.js";
import { runHirUtilitiesTests } from "./hir/utilities.js";
import { runIRTypesTests } from "./ir/types.js";
import { runIRInstructionsTests } from "./ir/instructions.js";
import { runIRBlocksTests } from "./ir/blocks.js";
import { runIRFunctionsTests } from "./ir/functions.js";
import { runMemoryPrimitivesTests } from "./memory/primitives.js";
import { runMemoryStructsTests } from "./memory/structs.js";
import { runMemoryEnumsTests } from "./memory/enums.js";
import { runMemoryArraysTests } from "./memory/arrays.js";
import { runMemoryStackAllocTests } from "./memory/stack_alloc.js";
import { runPrimitivesTests } from "./binary/primitives.js";
import { runTypesTests } from "./binary/types.js";
import { runInstructionsTests } from "./binary/instructions.js";
import { runRoundtripTests } from "./binary/roundtrip.js";

const { printSummary, clearErrors } = lib;

clearErrors();

let totalTests = 0;

totalTests += runKeywordsTests();
totalTests += runLiteralsTests();
totalTests += runOperatorsTests();
totalTests += runDelimitersTests();
totalTests += runCommentsTests();
totalTests += runErrorsTests();
totalTests += runPositionTests();
totalTests += runAstTests();
totalTests += runParserExpressionTests();
totalTests += runParserStatementTests();
totalTests += runParserItemTests();
totalTests += runParserPatternTests();
totalTests += runParserTypeTests();
totalTests += runParserErrorTests();
totalTests += runTypeRepresentationTests();
totalTests += runTypeContextTests();
totalTests += runTypeUtilitiesTests();
totalTests += runHirConstructionTests();
totalTests += runHirUtilitiesTests();
totalTests += runIRTypesTests();
totalTests += runIRInstructionsTests();
totalTests += runIRBlocksTests();
totalTests += runIRFunctionsTests();
totalTests += runMemoryPrimitivesTests();
totalTests += runMemoryStructsTests();
totalTests += runMemoryEnumsTests();
totalTests += runMemoryArraysTests();
totalTests += runMemoryStackAllocTests();
totalTests += runPrimitivesTests();
totalTests += runTypesTests();
totalTests += runInstructionsTests();
totalTests += runRoundtripTests();

const success = printSummary(totalTests);
process.exit(success ? 0 : 1);
