import * as lib from "./lib.js";
import { runKeywordsTests } from "./keywords.js";
import { runLiteralsTests } from "./literals.js";
import { runOperatorsTests } from "./operators.js";
import { runDelimitersTests } from "./delimiters.js";
import { runCommentsTests } from "./comments.js";
import { runErrorsTests } from "./errors.js";
import { runPositionTests } from "./position.js";
import { runAstTests } from "./ast.js";
import { runParserExpressionTests } from "./parser/expressions.js";
import { runParserStatementTests } from "./parser/statements.js";
import { runParserItemTests } from "./parser/items.js";
import { runParserPatternTests } from "./parser/patterns.js";
import { runParserTypeTests } from "./parser/types.js";
import { runParserErrorTests } from "./parser/errors.js";
import { runTypeRepresentationTests } from "./types/representation.js";
import { runTypeContextTests } from "./types/context.js";
import { runTypeUtilitiesTests } from "./types/utilities.js";
import { runHirConstructionTests } from "./hir/construction.js";
import { runHirUtilitiesTests } from "./hir/utilities.js";
import { runIRTypesTests } from "./ir/types.js";
import { runIRInstructionsTests } from "./ir/instructions.js";
import { runIRBlocksTests } from "./ir/blocks.js";
import { runIRFunctionsTests } from "./ir/functions.js";
import { runMemoryPrimitivesTests } from "./memory/primitives.js";
import { runMemoryStructsTests } from "./memory/structs.js";
import { runMemoryEnumsTests } from "./memory/enums.js";
import { runMemoryArraysTests } from "./memory/arrays.js";
import { runMemoryStackAllocTests } from "./memory/stack_alloc.js";
import { runPrimitivesTests } from "./binary/primitives.js";
import { runTypesTests } from "./binary/types.js";
import { runInstructionsTests } from "./binary/instructions.js";
import { runRoundtripTests } from "./binary/roundtrip.js";
import { runBinaryConformanceTests } from "./binary/conformance.js";
import { runOutputTypesTests } from "./output/types.js";
import { runOutputInstructionsTests } from "./output/instructions.js";
import { runOutputFunctionsTests } from "./output/functions.js";
import { runValidationBasicTests } from "./validation/basic.js";
import { runValidationTypesTests } from "./validation/types.js";
import { runValidationControlFlowTests } from "./validation/control_flow.js";
import { runValidationDominanceTests } from "./validation/dominance.js";
import { runInferenceExpressionsTests } from "./inference/expressions.js";
import { runInferenceStatementsTests } from "./inference/statements.js";
import { runInferenceFunctionsTests } from "./inference/functions.js";
import { runInferenceErrorsTests } from "./inference/errors.js";
import { runInferenceStructsTests } from "./inference/structs.js";
import { runInferenceEnumsTests } from "./inference/enums.js";
import { runInferenceReferencesTests } from "./inference/references.js";
import { runTests as runLoweringExpressionsTests } from "./lowering/expressions.js";
import { runTests as runLoweringStatementsTests } from "./lowering/statements.js";
import { runTests as runLoweringControlFlowTests } from "./lowering/control_flow.js";
import { runTests as runLoweringPatternsTests } from "./lowering/patterns.js";
import { runTests as runIRBuilderConstantsTests } from "./ir_builder/constants.js";
import { runTests as runIRBuilderArithmeticTests } from "./ir_builder/arithmetic.js";
import { runTests as runIRBuilderControlFlowTests } from "./ir_builder/control_flow.js";
import { runTests as runIRBuilderVariablesTests } from "./ir_builder/variables.js";
import { runTests as runIRBuilderMemoryTests } from "./ir_builder/memory.js";
import { runTests as runHirToSsaExpressionsTests } from "./hir_to_ssa/expressions.js";
import { runDiagnosticsCollectionTests } from "./diagnostics/collection.js";
import { runDiagnosticsRenderingTests } from "./diagnostics/rendering.js";
import { runE2ETests } from "./e2e.js";
import { runExamplesTests } from "./examples.js";

const { printSummary, clearErrors, beginRun, endRun } = lib;

clearErrors();
beginRun();

runKeywordsTests();
runLiteralsTests();
runOperatorsTests();
runDelimitersTests();
runCommentsTests();
runErrorsTests();
runPositionTests();
runAstTests();
runParserExpressionTests();
runParserStatementTests();
runParserItemTests();
runParserPatternTests();
runParserTypeTests();
runParserErrorTests();
runTypeRepresentationTests();
runTypeContextTests();
runTypeUtilitiesTests();
runHirConstructionTests();
runHirUtilitiesTests();
runIRTypesTests();
runIRInstructionsTests();
runIRBlocksTests();
runIRFunctionsTests();
runMemoryPrimitivesTests();
runMemoryStructsTests();
runMemoryEnumsTests();
runMemoryArraysTests();
runMemoryStackAllocTests();
runPrimitivesTests();
runTypesTests();
runInstructionsTests();
runRoundtripTests();
runBinaryConformanceTests();
runOutputTypesTests();
runOutputInstructionsTests();
runOutputFunctionsTests();
runValidationBasicTests();
runValidationTypesTests();
runValidationControlFlowTests();
runValidationDominanceTests();
runInferenceExpressionsTests();
runInferenceStatementsTests();
runInferenceFunctionsTests();
runInferenceErrorsTests();
runInferenceStructsTests();
runInferenceEnumsTests();
runInferenceReferencesTests();
runLoweringExpressionsTests();
runLoweringStatementsTests();
runLoweringControlFlowTests();
runLoweringPatternsTests();
runIRBuilderConstantsTests();
runIRBuilderArithmeticTests();
runIRBuilderControlFlowTests();
runIRBuilderVariablesTests();
runIRBuilderMemoryTests();
runHirToSsaExpressionsTests();
runDiagnosticsCollectionTests();
runDiagnosticsRenderingTests();
runE2ETests();
runExamplesTests();

endRun();
const success = printSummary();
process.exit(success ? 0 : 1);
